const seminarAction = {
    CREATE_SEMINAR: 'CREATE_SEMINAR',
    READ_SEMINAR: 'READ_SEMINAR',
    UPADATE_SEMINAR: 'UPADATE_SEMINAR',
    DELETE_SEMINAR : 'DELETE_SEMINAR'
};

export default seminarAction;