const seminarAction = {
    CREATE_SEMINAR: 'CREATE_SEMINAR',
    READ_SEMINAR: 'READ_SEMINAR',
    SELECT_SEMINAR: 'SELECT_SEMINAR',
    UPADATE_SEMINAR: 'UPADATE_SEMINAR',
    DELETE_SEMINAR: 'DELETE_SEMINAR',
    INVALIDATE_SEMINAR: 'INVALIDATE_SEMINAR',
    RECEIVE_SEMINAR : 'RECEIVE_SEMINAR'
};

export default seminarAction;